// <auto-generated />
using APIFizyo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIFizyo.Migrations
{
    [DbContext(typeof(APIFizyoDBContext))]
    [Migration("20220118124409_bir")]
    partial class bir
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("APIFizyo.Model.Kullanıcı", b =>
                {
                    b.Property<int>("KullanıcıID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KullanıcıID"), 1L, 1);

                    b.Property<string>("Eposta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RolID")
                        .HasColumnType("int");

                    b.Property<string>("Şifre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("KullanıcıID");

                    b.HasIndex("RolID");

                    b.ToTable("Kullanıcılar");

                    b.HasData(
                        new
                        {
                            KullanıcıID = 1,
                            Eposta = "sinan@outlook.com",
                            RolID = 1,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 2,
                            Eposta = "ali@hotmail.com",
                            RolID = 1,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 3,
                            Eposta = "mahmut@hotmail.com",
                            RolID = 3,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 4,
                            Eposta = "mansurkürşad@icloud.com",
                            RolID = 2,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 5,
                            Eposta = "gamze@gmail.com",
                            RolID = 4,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 6,
                            Eposta = "miraç@hotmail.com",
                            RolID = 3,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 7,
                            Eposta = "yücel@outlook.com",
                            RolID = 1,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 8,
                            Eposta = "kubilay@gmail.com",
                            RolID = 4,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 9,
                            Eposta = "hayati@hotmail.com",
                            RolID = 3,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 10,
                            Eposta = "bedriyemüge@hotmail.com",
                            RolID = 2,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 11,
                            Eposta = "birsen@icloud.com",
                            RolID = 1,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 12,
                            Eposta = "serdal@gmail.com",
                            RolID = 2,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 13,
                            Eposta = "bünyamin@gmail.com",
                            RolID = 3,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 14,
                            Eposta = "özgür@gmail.com",
                            RolID = 2,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 15,
                            Eposta = "ferdi@gmail.com",
                            RolID = 1,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 16,
                            Eposta = "reyhan@outlook.com",
                            RolID = 2,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 17,
                            Eposta = "ilhan@gmail.com",
                            RolID = 2,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 18,
                            Eposta = "gülşah@icloud.com",
                            RolID = 4,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 19,
                            Eposta = "nalan@outlook.com",
                            RolID = 3,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 20,
                            Eposta = "semih@outlook.com",
                            RolID = 2,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 21,
                            Eposta = "ergün@outlook.com",
                            RolID = 1,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 22,
                            Eposta = "fatih@hotmail.com",
                            RolID = 3,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 23,
                            Eposta = "şenay@gmail.com",
                            RolID = 4,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 24,
                            Eposta = "serkan@outlook.com",
                            RolID = 4,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 25,
                            Eposta = "emre@icloud.com",
                            RolID = 4,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 26,
                            Eposta = "bahattin@gmail.com",
                            RolID = 4,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 27,
                            Eposta = "irazca@gmail.com",
                            RolID = 1,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 28,
                            Eposta = "hatice@icloud.com",
                            RolID = 3,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 29,
                            Eposta = "bariş@icloud.com",
                            RolID = 3,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 30,
                            Eposta = "rezan@hotmail.com",
                            RolID = 3,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 31,
                            Eposta = "fatih@gmail.com",
                            RolID = 2,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 32,
                            Eposta = "fuat@outlook.com",
                            RolID = 1,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 33,
                            Eposta = "gökhan@icloud.com",
                            RolID = 1,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 34,
                            Eposta = "orhan@outlook.com",
                            RolID = 4,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 35,
                            Eposta = "mehmet@hotmail.com",
                            RolID = 3,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 36,
                            Eposta = "evren@hotmail.com",
                            RolID = 3,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 37,
                            Eposta = "oktay@gmail.com",
                            RolID = 1,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 38,
                            Eposta = "harun@gmail.com",
                            RolID = 1,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 39,
                            Eposta = "yavuz@hotmail.com",
                            RolID = 4,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 40,
                            Eposta = "pinar@hotmail.com",
                            RolID = 4,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 41,
                            Eposta = "mehmet@icloud.com",
                            RolID = 2,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 42,
                            Eposta = "umut@outlook.com",
                            RolID = 2,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 43,
                            Eposta = "mesude@hotmail.com",
                            RolID = 4,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 44,
                            Eposta = "hüseyincahit@gmail.com",
                            RolID = 4,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 45,
                            Eposta = "haşimonur@gmail.com",
                            RolID = 2,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 46,
                            Eposta = "eyyupsabri@gmail.com",
                            RolID = 3,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 47,
                            Eposta = "mustafa@icloud.com",
                            RolID = 2,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 48,
                            Eposta = "mustafa@icloud.com",
                            RolID = 2,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 49,
                            Eposta = "ufuk@icloud.com",
                            RolID = 1,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 50,
                            Eposta = "ahmetali@hotmail.com",
                            RolID = 2,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 51,
                            Eposta = "mediha@icloud.com",
                            RolID = 2,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 52,
                            Eposta = "hasan@icloud.com",
                            RolID = 3,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 53,
                            Eposta = "kamil@icloud.com",
                            RolID = 3,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 54,
                            Eposta = "nebi@icloud.com",
                            RolID = 1,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 55,
                            Eposta = "özcan@gmail.com",
                            RolID = 4,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 56,
                            Eposta = "nagihan@gmail.com",
                            RolID = 3,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 57,
                            Eposta = "ceren@gmail.com",
                            RolID = 2,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 58,
                            Eposta = "serkan@hotmail.com",
                            RolID = 3,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 59,
                            Eposta = "hasan@icloud.com",
                            RolID = 3,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 60,
                            Eposta = "yusufkenan@gmail.com",
                            RolID = 4,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 61,
                            Eposta = "çetin@icloud.com",
                            RolID = 1,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 62,
                            Eposta = "tarkan@gmail.com",
                            RolID = 2,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 63,
                            Eposta = "meralleman@hotmail.com",
                            RolID = 2,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 64,
                            Eposta = "ergün@icloud.com",
                            RolID = 4,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 65,
                            Eposta = "kenanahmet@icloud.com",
                            RolID = 4,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 66,
                            Eposta = "ural@icloud.com",
                            RolID = 4,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 67,
                            Eposta = "yahya@icloud.com",
                            RolID = 2,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 68,
                            Eposta = "bengü@outlook.com",
                            RolID = 2,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 69,
                            Eposta = "fatihnazmi@hotmail.com",
                            RolID = 2,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 70,
                            Eposta = "dilek@outlook.com",
                            RolID = 1,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 71,
                            Eposta = "mehmet@icloud.com",
                            RolID = 1,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 72,
                            Eposta = "tufanakin@hotmail.com",
                            RolID = 4,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 73,
                            Eposta = "mehmet@hotmail.com",
                            RolID = 1,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 74,
                            Eposta = "turgayyilmaz@icloud.com",
                            RolID = 4,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 75,
                            Eposta = "güldehen@icloud.com",
                            RolID = 4,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 76,
                            Eposta = "gökmen@hotmail.com",
                            RolID = 2,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 77,
                            Eposta = "bülent@gmail.com",
                            RolID = 2,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 78,
                            Eposta = "erol@icloud.com",
                            RolID = 2,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 79,
                            Eposta = "bahri@icloud.com",
                            RolID = 1,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 80,
                            Eposta = "özenözlem@gmail.com",
                            RolID = 2,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 81,
                            Eposta = "selma@icloud.com",
                            RolID = 3,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 82,
                            Eposta = "tuğsem@hotmail.com",
                            RolID = 1,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 83,
                            Eposta = "teslimenazli@gmail.com",
                            RolID = 4,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 84,
                            Eposta = "gülçin@hotmail.com",
                            RolID = 3,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 85,
                            Eposta = "ismail@icloud.com",
                            RolID = 3,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 86,
                            Eposta = "murat@gmail.com",
                            RolID = 4,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 87,
                            Eposta = "ebru@icloud.com",
                            RolID = 2,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 88,
                            Eposta = "tümay@gmail.com",
                            RolID = 2,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 89,
                            Eposta = "ahmet@gmail.com",
                            RolID = 4,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 90,
                            Eposta = "ebru@icloud.com",
                            RolID = 2,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 91,
                            Eposta = "hüseyinyavuz@gmail.com",
                            RolID = 3,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 92,
                            Eposta = "başak@outlook.com",
                            RolID = 1,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 93,
                            Eposta = "ayşegül@hotmail.com",
                            RolID = 1,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 94,
                            Eposta = "evrim@icloud.com",
                            RolID = 4,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 95,
                            Eposta = "yaser@hotmail.com",
                            RolID = 3,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 96,
                            Eposta = "ülkü@icloud.com",
                            RolID = 3,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 97,
                            Eposta = "özhan@icloud.com",
                            RolID = 1,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 98,
                            Eposta = "ufuk@gmail.com",
                            RolID = 4,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 99,
                            Eposta = "aksel@hotmail.com",
                            RolID = 3,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 100,
                            Eposta = "fulya@icloud.com",
                            RolID = 3,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 101,
                            Eposta = "burcu@icloud.com",
                            RolID = 3,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 102,
                            Eposta = "taylan@hotmail.com",
                            RolID = 4,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 103,
                            Eposta = "yilmaz@icloud.com",
                            RolID = 2,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 104,
                            Eposta = "zeynep@gmail.com",
                            RolID = 4,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 105,
                            Eposta = "bayram@icloud.com",
                            RolID = 3,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 106,
                            Eposta = "gülay@hotmail.com",
                            RolID = 3,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 107,
                            Eposta = "rabia@outlook.com",
                            RolID = 1,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 108,
                            Eposta = "sevda@outlook.com",
                            RolID = 2,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 109,
                            Eposta = "serhat@hotmail.com",
                            RolID = 2,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 110,
                            Eposta = "engin@icloud.com",
                            RolID = 3,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 111,
                            Eposta = "asli@hotmail.com",
                            RolID = 2,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 112,
                            Eposta = "tuba@icloud.com",
                            RolID = 2,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 113,
                            Eposta = "bariş@hotmail.com",
                            RolID = 4,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 114,
                            Eposta = "sevgi@hotmail.com",
                            RolID = 4,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 115,
                            Eposta = "kalender@outlook.com",
                            RolID = 3,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 116,
                            Eposta = "halil@icloud.com",
                            RolID = 4,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 117,
                            Eposta = "bilge@icloud.com",
                            RolID = 1,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 118,
                            Eposta = "ferda@gmail.com",
                            RolID = 4,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 119,
                            Eposta = "ezgi@hotmail.com",
                            RolID = 2,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 120,
                            Eposta = "aysun@outlook.com",
                            RolID = 4,
                            Şifre = "Qwe123"
                        });
                });

            modelBuilder.Entity("APIFizyo.Model.Rol", b =>
                {
                    b.Property<int>("RolID")
                        .HasColumnType("int");

                    b.Property<string>("RolAdı")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("RolID");

                    b.ToTable("Roller");

                    b.HasData(
                        new
                        {
                            RolID = 1,
                            RolAdı = "UserCandidate"
                        },
                        new
                        {
                            RolID = 2,
                            RolAdı = "UserNormal"
                        },
                        new
                        {
                            RolID = 3,
                            RolAdı = "Admin"
                        },
                        new
                        {
                            RolID = 4,
                            RolAdı = "Supervisor"
                        });
                });

            modelBuilder.Entity("APIFizyo.Model.Kullanıcı", b =>
                {
                    b.HasOne("APIFizyo.Model.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });
#pragma warning restore 612, 618
        }
    }
}
